version: "3.9"

services:
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMMIT_ID: ${COMMIT_ID}
        DOCKER_USERNAME: ${DOCKER_USERNAME}
    image: ${DOCKER_USERNAME}/ecommerce:${COMMIT_ID}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - ecommerce
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mongo_data:
