version: "3.9"

services:
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMMIT_ID: ${COMMIT_ID}
        DOCKER_USERNAME: ${DOCKER_USERNAME}
    image: ${DOCKER_USERNAME}/ecommerce:${COMMIT_ID}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - ecommerce
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDISPASSWORD=root
    command: >
      redis-server --requirepass root
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  elasticsearch_data:
  redis_data:
