const mongoose = require("mongoose");
const bcrypt = require("bcrypt");
const ProductCategory = require("./../models/product-category.model");
const Product = require("./../models/product.model");
const User = require("./../models/user.model");

mongoose
  .connect(process.env.MONGODB_URL || "mongodb://root:root@localhost:27017")
  .then(() => {
    console.log("Connected to MongoDB");
  })
  .catch((err) => {
    console.error("Error connecting to MongoDB", err);
  });

const mockUsers = [
  {
    email: "rbutters0@icq.com",
    password: 'eU5"+xp1$m7"u',
    first_name: "Rowena",
    last_name: "Butters",
    date_of_birth: "6/20/1996",
    gender: "Female",
    avatar: "https://robohash.org/omnisauttenetur.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "llimming1@github.io",
    password: "rS3$HA,T",
    first_name: "Lyn",
    last_name: "Limming",
    date_of_birth: "9/26/1997",
    gender: "Agender",
    avatar: "https://robohash.org/inutitaque.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "ckippie2@sina.com.cn",
    password: "zD8#dE1q",
    first_name: "Cornie",
    last_name: "Kippie",
    date_of_birth: "6/18/1996",
    gender: "Female",
    avatar: "https://robohash.org/fugitipsammolestiae.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "lsouthwick3@privacy.gov.au",
    password: "iO9$/V>b",
    first_name: "Loren",
    last_name: "Southwick",
    date_of_birth: "12/17/1995",
    gender: "Male",
    avatar: "https://robohash.org/quossedanimi.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "ddencs4@ehow.com",
    password: "mL9).#Rv",
    first_name: "Demetre",
    last_name: "Dencs",
    date_of_birth: "7/14/2002",
    gender: "Male",
    avatar: "https://robohash.org/estaliquidmolestiae.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "mbuckland5@fotki.com",
    password: "xR7#PMjn>",
    first_name: "Marris",
    last_name: "Buckland",
    date_of_birth: "8/4/2002",
    gender: "Female",
    avatar:
      "https://robohash.org/autemsimiliquevoluptatem.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "dohartnett6@creativecommons.org",
    password: "mP0%qyp&",
    first_name: "Dal",
    last_name: "O'Hartnett",
    date_of_birth: "7/31/1999",
    gender: "Male",
    avatar:
      "https://robohash.org/consequunturofficiisat.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "ojopke7@cloudflare.com",
    password: "bI7(pr\\f0p1o",
    first_name: "Oralie",
    last_name: "Jopke",
    date_of_birth: "1/11/1993",
    gender: "Genderfluid",
    avatar: "https://robohash.org/etabquidem.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "nisakowicz8@ox.ac.uk",
    password: "dR4,q|#@@",
    first_name: "Natalie",
    last_name: "Isakowicz",
    date_of_birth: "9/18/1999",
    gender: "Female",
    avatar: "https://robohash.org/quamminuspariatur.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "ctungate9@list-manage.com",
    password: "jX1*p3g&s",
    first_name: "Cleavland",
    last_name: "Tungate",
    date_of_birth: "10/9/1995",
    gender: "Male",
    avatar: "https://robohash.org/eligendisaepedolor.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "sbowsera@ustream.tv",
    password: 'vN3"n4~{M+',
    first_name: "Sande",
    last_name: "Bowser",
    date_of_birth: "1/2/1991",
    gender: "Female",
    avatar: "https://robohash.org/autquasdoloremque.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "pelintuneb@is.gd",
    password: "bL4_2y1`xe",
    first_name: "Paule",
    last_name: "Elintune",
    date_of_birth: "12/7/1996",
    gender: "Female",
    avatar:
      "https://robohash.org/etconsequatureligendi.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "mmurtyc@virginia.edu",
    password: "tJ6#(*#Yu>TD+PnX",
    first_name: "Murray",
    last_name: "Murty",
    date_of_birth: "11/4/1990",
    gender: "Male",
    avatar: "https://robohash.org/nostrumrecusandaeet.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "rcoslettd@miitbeian.gov.cn",
    password: "yE9,+(g*@&g",
    first_name: "Rob",
    last_name: "Coslett",
    date_of_birth: "8/17/2000",
    gender: "Male",
    avatar: "https://robohash.org/quiquiperferendis.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "gsproate@globo.com",
    password: "qS0_C<69`8{",
    first_name: "Godiva",
    last_name: "Sproat",
    date_of_birth: "11/16/1997",
    gender: "Female",
    avatar: "https://robohash.org/sedlaudantiumeum.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "nchadwellf@marriott.com",
    password: "eN1|`E3gT*o!D<",
    first_name: "Nicol",
    last_name: "Chadwell",
    date_of_birth: "1/30/1999",
    gender: "Male",
    avatar: "https://robohash.org/minimasuscipitut.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "ssivillg@buzzfeed.com",
    password: "rF2&3K#s",
    first_name: "Susann",
    last_name: "Sivill",
    date_of_birth: "5/2/1993",
    gender: "Female",
    avatar: "https://robohash.org/quiliberoearum.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "gchatainierh@yahoo.co.jp",
    password: "aW4|A2r$nf",
    first_name: "Gay",
    last_name: "Chatainier",
    date_of_birth: "4/30/2002",
    gender: "Male",
    avatar: "https://robohash.org/architectoquamaut.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "mchettlei@google.com.au",
    password: "rM8?\\9wKO~",
    first_name: "Moise",
    last_name: "Chettle",
    date_of_birth: "1/29/1996",
    gender: "Male",
    avatar: "https://robohash.org/autetsit.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "tdochertyj@icq.com",
    password: "xC7*a$6<XFRq+\\",
    first_name: "Tuckie",
    last_name: "Docherty",
    date_of_birth: "11/8/1994",
    gender: "Male",
    avatar: "https://robohash.org/omnismagnamfugit.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "ystuckowk@imgur.com",
    password: "oJ9=Y.%ecBB<cR",
    first_name: "Yehudi",
    last_name: "Stuckow",
    date_of_birth: "12/14/2000",
    gender: "Male",
    avatar: "https://robohash.org/nihilmaioressequi.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "msawardl@vinaora.com",
    password: "eB3<M.35s",
    first_name: "Merla",
    last_name: "Saward",
    date_of_birth: "4/26/2003",
    gender: "Female",
    avatar: "https://robohash.org/quoquiullam.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "zmcguinleym@flavors.me",
    password: "zG1(%\\n{~/",
    first_name: "Zebedee",
    last_name: "McGuinley",
    date_of_birth: "6/28/1994",
    gender: "Male",
    avatar: "https://robohash.org/abpariatureos.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "rtiptonn@gizmodo.com",
    password: "nZ3<(8r`=\\m7T1",
    first_name: "Rogers",
    last_name: "Tipton",
    date_of_birth: "7/19/2001",
    gender: "Bigender",
    avatar: "https://robohash.org/minusporroqui.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "jglyneo@reverbnation.com",
    password: "lC1$n~|)mKyn",
    first_name: "Juline",
    last_name: "Glyne",
    date_of_birth: "4/9/2002",
    gender: "Female",
    avatar: "https://robohash.org/minimainventoresed.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "rcecerep@elegantthemes.com",
    password: "kW5)X~`Im",
    first_name: "Reid",
    last_name: "Cecere",
    date_of_birth: "9/30/1995",
    gender: "Male",
    avatar: "https://robohash.org/cupiditatecumqueaut.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "mclaidenq@usatoday.com",
    password: 'oE5"Z\\7th',
    first_name: "Marietta",
    last_name: "Claiden",
    date_of_birth: "4/26/1993",
    gender: "Male",
    avatar:
      "https://robohash.org/possimusaspernaturmolestiae.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "tcallingtonr@sohu.com",
    password: "uL0&3m4|nZ9B",
    first_name: "Tristam",
    last_name: "Callington",
    date_of_birth: "3/8/1999",
    gender: "Male",
    avatar: "https://robohash.org/excepturicumdolorem.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "crenons@youku.com",
    password: "kV7~Y<'Q|DjAN5_",
    first_name: "Carri",
    last_name: "Renon",
    date_of_birth: "9/13/2003",
    gender: "Female",
    avatar:
      "https://robohash.org/laborumpariaturaliquid.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "hwastellt@npr.org",
    password: "mM9$2v,@AW)",
    first_name: "Hedda",
    last_name: "Wastell",
    date_of_birth: "7/20/2004",
    gender: "Polygender",
    avatar: "https://robohash.org/eaqueenimdolor.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "tvenneuru@is.gd",
    password: "kN1'WnAMq\"{~XLW",
    first_name: "Tabby",
    last_name: "Venneur",
    date_of_birth: "2/17/1993",
    gender: "Female",
    avatar: "https://robohash.org/maximeeosaperiam.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "ahanabyv@ameblo.jp",
    password: "pO4$9s997Q?V_L",
    first_name: "Archaimbaud",
    last_name: "Hanaby",
    date_of_birth: "12/23/2002",
    gender: "Male",
    avatar: "https://robohash.org/laboriosamquivel.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "ostandonw@vk.com",
    password: "iW4/lz!r|#44P2",
    first_name: "Ollie",
    last_name: "Standon",
    date_of_birth: "11/26/1993",
    gender: "Genderfluid",
    avatar:
      "https://robohash.org/recusandaeexercitationemminima.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "dthebeaux@yandex.ru",
    password: "zA0.z{JD.r,E_~",
    first_name: "Donna",
    last_name: "Thebeau",
    date_of_birth: "5/3/2005",
    gender: "Bigender",
    avatar:
      "https://robohash.org/veritatisvoluptatemvelit.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "arably@jimdo.com",
    password: "aD3\\?*d@'6t!F<",
    first_name: "Anatola",
    last_name: "Rabl",
    date_of_birth: "2/8/1996",
    gender: "Female",
    avatar:
      "https://robohash.org/architectooccaecatiet.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "caudusz@reddit.com",
    password: "rX2*5kCNjPog",
    first_name: "Celestina",
    last_name: "Audus",
    date_of_birth: "3/25/1998",
    gender: "Female",
    avatar: "https://robohash.org/laborumatanimi.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "pmichiel10@amazon.co.uk",
    password: "cU9=0#tAL|C",
    first_name: "Pierette",
    last_name: "Michiel",
    date_of_birth: "3/8/1993",
    gender: "Non-binary",
    avatar:
      "https://robohash.org/repudiandaevoluptatemveritatis.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "hmccahey11@google.nl",
    password: "xT5)q!)k'G",
    first_name: "Helga",
    last_name: "Mc Cahey",
    date_of_birth: "11/19/1998",
    gender: "Female",
    avatar: "https://robohash.org/nobisetquia.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "jriggott12@plala.or.jp",
    password: "jE7+\\R7y",
    first_name: "Jo",
    last_name: "Riggott",
    date_of_birth: "11/7/2004",
    gender: "Male",
    avatar:
      "https://robohash.org/accusamuseaaspernatur.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "jbevan13@elegantthemes.com",
    password: "yU9#@Go~2I",
    first_name: "Joete",
    last_name: "Bevan",
    date_of_birth: "1/20/1991",
    gender: "Female",
    avatar: "https://robohash.org/ipsametlabore.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "tkayes14@usda.gov",
    password: "qY6+8={x&Y3d",
    first_name: "Tandy",
    last_name: "Kayes",
    date_of_birth: "9/16/1990",
    gender: "Female",
    avatar: "https://robohash.org/adipisciineius.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "hantonetti15@boston.com",
    password: "kA3`_,lv.}",
    first_name: "Hewie",
    last_name: "Antonetti",
    date_of_birth: "12/29/1996",
    gender: "Male",
    avatar:
      "https://robohash.org/estadipisciconsectetur.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "rfrayling16@va.gov",
    password: "yV2#e>ro&xa&",
    first_name: "Reggie",
    last_name: "Frayling",
    date_of_birth: "4/4/2001",
    gender: "Male",
    avatar: "https://robohash.org/enimquoautem.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "rgrattage17@reverbnation.com",
    password: "zY0_XV|~E1?@",
    first_name: "Reggi",
    last_name: "Grattage",
    date_of_birth: "12/10/1991",
    gender: "Non-binary",
    avatar:
      "https://robohash.org/repudiandaeperspiciatisqui.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "zbrundall18@etsy.com",
    password: "rP5!oBs7}i0m2E",
    first_name: "Zachary",
    last_name: "Brundall",
    date_of_birth: "4/6/1994",
    gender: "Male",
    avatar:
      "https://robohash.org/reprehenderitdoloreut.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "zskryne19@npr.org",
    password: "nF1#?J&|xw5",
    first_name: "Zolly",
    last_name: "Skryne",
    date_of_birth: "10/24/1991",
    gender: "Bigender",
    avatar: "https://robohash.org/doloremquequierror.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "bvennard1a@hibu.com",
    password: "bI3(2.g`VK~H",
    first_name: "Brandais",
    last_name: "Vennard",
    date_of_birth: "6/3/2005",
    gender: "Female",
    avatar: "https://robohash.org/autestasperiores.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "gwaller1b@webeden.co.uk",
    password: "nO4}<N72",
    first_name: "Gale",
    last_name: "Waller",
    date_of_birth: "4/15/2005",
    gender: "Male",
    avatar: "https://robohash.org/quiadoloremqui.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "olemonnier1c@cnet.com",
    password: "yF2=j/Ng(nblcnT",
    first_name: "Otes",
    last_name: "Lemonnier",
    date_of_birth: "8/10/2004",
    gender: "Male",
    avatar: "https://robohash.org/namsuntaliquam.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "bmatejic1d@networkadvertising.org",
    password: 'dS3\\"1Mr8Ie',
    first_name: "Bret",
    last_name: "Matejic",
    date_of_birth: "1/10/1994",
    gender: "Bigender",
    avatar: "https://robohash.org/atquemollitiaest.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "whilldrop1e@twitter.com",
    password: "eX4,H,T+LAh~S{f",
    first_name: "Winnie",
    last_name: "Hilldrop",
    date_of_birth: "5/21/1998",
    gender: "Female",
    avatar: "https://robohash.org/quodsuscipitoptio.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "dcrim1f@webnode.com",
    password: "yD6($7oD5YqM,",
    first_name: "Doti",
    last_name: "Crim",
    date_of_birth: "2/23/2002",
    gender: "Female",
    avatar:
      "https://robohash.org/corruptirecusandaeaut.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "rdavidovits1g@creativecommons.org",
    password: 'mM3~M=,SwL_#l&"S',
    first_name: "Romy",
    last_name: "Davidovits",
    date_of_birth: "7/23/1999",
    gender: "Female",
    avatar: "https://robohash.org/etdolorescorrupti.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "sneward1h@pcworld.com",
    password: "qG0!OTRz",
    first_name: "Shanta",
    last_name: "Neward",
    date_of_birth: "5/26/2004",
    gender: "Female",
    avatar: "https://robohash.org/fugiatistemagni.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "hmillington1i@forbes.com",
    password: "jH0$SrbqmA&",
    first_name: "Hy",
    last_name: "Millington",
    date_of_birth: "5/3/2005",
    gender: "Male",
    avatar:
      "https://robohash.org/distinctioperferendisvitae.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "lrolfe1j@thetimes.co.uk",
    password: "pB7&SQ=3?V",
    first_name: "Leila",
    last_name: "Rolfe",
    date_of_birth: "5/15/2000",
    gender: "Female",
    avatar: "https://robohash.org/abullamtotam.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "rfeirn1k@themeforest.net",
    password: "dW5'p3X~",
    first_name: "Rozanna",
    last_name: "Feirn",
    date_of_birth: "2/12/1998",
    gender: "Female",
    avatar: "https://robohash.org/magniprovidentcumque.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "lfewkes1l@cisco.com",
    password: "tX7=.xDvhi",
    first_name: "Lew",
    last_name: "Fewkes",
    date_of_birth: "12/7/1991",
    gender: "Male",
    avatar: "https://robohash.org/essemagnamrerum.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "ckeating1m@deliciousdays.com",
    password: "sC6*\\U9YBa*",
    first_name: "Carr",
    last_name: "Keating",
    date_of_birth: "10/8/1993",
    gender: "Male",
    avatar: "https://robohash.org/nihilquamvoluptatem.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "ilossman1n@yahoo.co.jp",
    password: "nA6{$JqccRh*e6",
    first_name: "Ivar",
    last_name: "Lossman",
    date_of_birth: "12/29/2002",
    gender: "Male",
    avatar:
      "https://robohash.org/voluptatemdistinctioaut.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "wtearney1o@networksolutions.com",
    password: "qR4.nFcM!",
    first_name: "Wendie",
    last_name: "Tearney",
    date_of_birth: "6/26/1994",
    gender: "Female",
    avatar: "https://robohash.org/dictatotampariatur.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "bcromar1p@devhub.com",
    password: "vM1/t!TE`K1O1so9",
    first_name: "Bret",
    last_name: "Cromar",
    date_of_birth: "10/7/1998",
    gender: "Male",
    avatar: "https://robohash.org/idodionisi.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "kpettegre1q@tripod.com",
    password: "vP1'Zm8X",
    first_name: "Kelley",
    last_name: "Pettegre",
    date_of_birth: "8/4/1993",
    gender: "Male",
    avatar: "https://robohash.org/autaperiamdoloremque.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "bfehners1r@wiley.com",
    password: "cG1{SKZ)$a",
    first_name: "Brendan",
    last_name: "Fehners",
    date_of_birth: "5/28/1997",
    gender: "Male",
    avatar:
      "https://robohash.org/dolormolestiasdolorem.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "dhartington1s@answers.com",
    password: "yZ6)/YrNwR",
    first_name: "Danita",
    last_name: "Hartington",
    date_of_birth: "10/8/2005",
    gender: "Female",
    avatar: "https://robohash.org/inciduntnamsed.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "ughio1t@rakuten.co.jp",
    password: "xW4=eaLHx+K8$5",
    first_name: "Urbano",
    last_name: "Ghio",
    date_of_birth: "7/7/1994",
    gender: "Male",
    avatar: "https://robohash.org/numquametaut.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "tpoletto1u@unc.edu",
    password: "jB1\\%(8h,JBGIU",
    first_name: "Tabbatha",
    last_name: "Poletto",
    date_of_birth: "3/5/2004",
    gender: "Female",
    avatar: "https://robohash.org/etnonillo.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "rwilton1v@ebay.co.uk",
    password: "bJ9@aMVXc=V0",
    first_name: "Rosa",
    last_name: "Wilton",
    date_of_birth: "12/5/1990",
    gender: "Female",
    avatar: "https://robohash.org/ducimusquasirerum.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "mbell1w@go.com",
    password: "kR3`9van_fVY",
    first_name: "Marylou",
    last_name: "Bell",
    date_of_birth: "12/14/1999",
    gender: "Female",
    avatar: "https://robohash.org/commodisitfugit.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "atotman1x@state.tx.us",
    password: 'fT7"~~vPx',
    first_name: "Auria",
    last_name: "Totman",
    date_of_birth: "6/22/1999",
    gender: "Female",
    avatar: "https://robohash.org/providentnonharum.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "nveness1y@biblegateway.com",
    password: 'dA0,?"e7x*UR3',
    first_name: "Nan",
    last_name: "Veness",
    date_of_birth: "9/28/2001",
    gender: "Female",
    avatar: "https://robohash.org/facilisquidemsint.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "tthom1z@prweb.com",
    password: "qL8!?H35?i,O<'",
    first_name: "Tris",
    last_name: "Thom",
    date_of_birth: "10/2/1994",
    gender: "Male",
    avatar: "https://robohash.org/autininventore.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "llohden20@technorati.com",
    password: "cZ3*>gK$r8C",
    first_name: "Legra",
    last_name: "Lohden",
    date_of_birth: "7/28/1995",
    gender: "Female",
    avatar:
      "https://robohash.org/occaecatiducimusmolestiae.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "asach21@newyorker.com",
    password: "iX1?83n@s",
    first_name: "Annecorinne",
    last_name: "Sach",
    date_of_birth: "7/1/1998",
    gender: "Female",
    avatar: "https://robohash.org/hicautemsunt.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "bstaziker22@purevolume.com",
    password: "nI6'3>I3*I9uWJMa",
    first_name: "Beltran",
    last_name: "Staziker",
    date_of_birth: "8/20/1995",
    gender: "Male",
    avatar: "https://robohash.org/necessitatibusutsit.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "wlodewick23@ucsd.edu",
    password: "rS8\\3H`XqRB",
    first_name: "Westbrook",
    last_name: "Lodewick",
    date_of_birth: "3/29/1997",
    gender: "Male",
    avatar:
      "https://robohash.org/repellendusquisquamut.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "cbrient24@hp.com",
    password: "tA6@?D\\j)wc#z}\\$",
    first_name: "Chip",
    last_name: "Brient",
    date_of_birth: "2/10/1999",
    gender: "Male",
    avatar:
      "https://robohash.org/occaecatiassumendamodi.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "ahevey25@opera.com",
    password: "oN0#RGhcf",
    first_name: "Aurelie",
    last_name: "Hevey",
    date_of_birth: "2/27/2001",
    gender: "Female",
    avatar: "https://robohash.org/quisofficiaoccaecati.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "btylor26@goo.gl",
    password: "lJ4*?_Z\\\\UFsk@",
    first_name: "Barbaraanne",
    last_name: "Tylor",
    date_of_birth: "3/17/1996",
    gender: "Female",
    avatar: "https://robohash.org/officiaundesed.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "llashford27@com.com",
    password: "hW6\\cgpo",
    first_name: "Land",
    last_name: "Lashford",
    date_of_birth: "6/19/2003",
    gender: "Male",
    avatar: "https://robohash.org/autsitmagni.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "mkigelman28@webeden.co.uk",
    password: "tI7+?DNYq",
    first_name: "Munroe",
    last_name: "Kigelman",
    date_of_birth: "12/17/1991",
    gender: "Male",
    avatar:
      "https://robohash.org/delectusharumassumenda.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "atippett29@hp.com",
    password: "dG2<{Qp'cAeaxBa",
    first_name: "Annmaria",
    last_name: "Tippett",
    date_of_birth: "3/12/1994",
    gender: "Female",
    avatar: "https://robohash.org/quasiharumut.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "hgencke2a@wired.com",
    password: "yI3_Xt$66f7Eif",
    first_name: "Hayden",
    last_name: "Gencke",
    date_of_birth: "1/9/2005",
    gender: "Male",
    avatar: "https://robohash.org/sintmaximeut.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "nsineath2b@msn.com",
    password: "iV2`BH*50!Pj\\L",
    first_name: "Nomi",
    last_name: "Sineath",
    date_of_birth: "5/22/1993",
    gender: "Female",
    avatar: "https://robohash.org/ipsumeosrepellat.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "rdymick2c@wikipedia.org",
    password: "rL8<Y9w7+Fs~2$",
    first_name: "Rafi",
    last_name: "Dymick",
    date_of_birth: "12/11/1990",
    gender: "Male",
    avatar:
      "https://robohash.org/similiquevoluptatemharum.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "njaniszewski2d@odnoklassniki.ru",
    password: "oE9&S%UWW$F|k>iQ",
    first_name: "Nathalie",
    last_name: "Janiszewski",
    date_of_birth: "10/19/1995",
    gender: "Female",
    avatar: "https://robohash.org/quisquamnamdeserunt.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "lheasley2e@tamu.edu",
    password: 'vW8`,"pya_X2L',
    first_name: "Lelia",
    last_name: "Heasley",
    date_of_birth: "7/16/1992",
    gender: "Female",
    avatar: "https://robohash.org/quidemquivel.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "edenyagin2f@tiny.cc",
    password: "wT5,a(6@|G={e",
    first_name: "Emera",
    last_name: "Denyagin",
    date_of_birth: "4/25/1992",
    gender: "Female",
    avatar: "https://robohash.org/cumquiaeaque.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "asergean2g@unc.edu",
    password: "jD2#ZZ/KD",
    first_name: "Arty",
    last_name: "Sergean",
    date_of_birth: "6/1/1991",
    gender: "Male",
    avatar: "https://robohash.org/estitaquequia.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "sdommerque2h@guardian.co.uk",
    password: "cI9~bY5%W",
    first_name: "Stacee",
    last_name: "Dommerque",
    date_of_birth: "5/29/2003",
    gender: "Female",
    avatar: "https://robohash.org/eumabamet.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "haverill2i@cnn.com",
    password: "jX1'O@?9k&yhCr",
    first_name: "Hew",
    last_name: "Averill",
    date_of_birth: "11/24/2000",
    gender: "Male",
    avatar: "https://robohash.org/oditnamtempora.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "wgossipin2j@discuz.net",
    password: "eP6%9*V|p6)u",
    first_name: "Welch",
    last_name: "Gossipin",
    date_of_birth: "7/11/1995",
    gender: "Male",
    avatar: "https://robohash.org/quasiipsaqui.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "pdelacote2k@eventbrite.com",
    password: "iS1(Lvmp\\iskyq",
    first_name: "Percival",
    last_name: "De La Cote",
    date_of_birth: "10/11/1994",
    gender: "Male",
    avatar:
      "https://robohash.org/expeditavoluptatemeaque.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "agrindle2l@army.mil",
    password: "nZ3'\"2unu`9<",
    first_name: "Andree",
    last_name: "Grindle",
    date_of_birth: "11/11/2005",
    gender: "Female",
    avatar:
      "https://robohash.org/accusantiumvoluptasconsequatur.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "athrelkeld2m@technorati.com",
    password: "uZ8_kPQv|H}>+T",
    first_name: "Ambros",
    last_name: "Threlkeld",
    date_of_birth: "11/21/2003",
    gender: "Male",
    avatar: "https://robohash.org/providentoditex.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "rlainton2n@mail.ru",
    password: "gZ7+rZN3Da\\\\<T",
    first_name: "Rosemonde",
    last_name: "Lainton",
    date_of_birth: "12/2/2004",
    gender: "Female",
    avatar:
      "https://robohash.org/doloradipiscilaboriosam.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "smckimm2o@yahoo.co.jp",
    password: "tO5~VU>uB8",
    first_name: "Shannah",
    last_name: "McKimm",
    date_of_birth: "3/12/1991",
    gender: "Genderqueer",
    avatar: "https://robohash.org/inipsamvitae.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "tocollopy2p@unblog.fr",
    password: "zZ8%4zeZZHmXB3.",
    first_name: "Tarrance",
    last_name: "O'Collopy",
    date_of_birth: "3/12/1997",
    gender: "Male",
    avatar: "https://robohash.org/quisisteut.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "fbarrim2q@google.pl",
    password: "mJ0$<SF_'4L",
    first_name: "Farly",
    last_name: "Barrim",
    date_of_birth: "8/12/2003",
    gender: "Male",
    avatar: "https://robohash.org/velitquocommodi.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
  {
    email: "hfrostdicke2r@washington.edu",
    password: "gZ0.CQ/&{I4",
    first_name: "Ham",
    last_name: "Frostdicke",
    date_of_birth: "11/16/2004",
    gender: "Male",
    avatar: "https://robohash.org/quototamculpa.png?size=50x50&set=set1",
    is_admin: false,
    is_verified: true,
  },
];

const mockProductCategories = [
  {
    name: "T-Shirts",
    description: "Short-sleeved or long-sleeved casual tops.",
    is_admin: false,
    is_verified: true,
  },
  { name: "Shirts", description: "Formal or casual button-up shirts." },
  { name: "Pants", description: "Long trousers for men and women." },
  { name: "Jeans", description: "Denim pants suitable for casual wear." },
  {
    name: "Shorts",
    description: "Short trousers for summer or casual occasions.",
    is_admin: false,
    is_verified: true,
  },
  { name: "Skirts", description: "Casual or formal wear for women." },
  { name: "Dresses", description: "One-piece outfits for various occasions." },
  { name: "Jackets", description: "Outerwear for warmth or style." },
  { name: "Sweaters", description: "Knitted tops for colder weather." },
  {
    name: "Hoodies",
    description: "Sweaters with hoods, great for casual wear.",
    is_admin: false,
    is_verified: true,
  },
  { name: "Coats", description: "Outerwear for winter or formal settings." },
  {
    name: "Blazers",
    description: "Formal jackets for professional or casual chic looks.",
    is_admin: false,
    is_verified: true,
  },
  {
    name: "Suits",
    description: "Matching sets of jacket and trousers for formal occasions.",
    is_admin: false,
    is_verified: true,
  },
  { name: "Activewear", description: "Clothes for exercise or sports." },
  {
    name: "Underwear",
    description: "Basic inner clothing like briefs and bras.",
    is_admin: false,
    is_verified: true,
  },
  { name: "Swimwear", description: "Clothes for swimming or beachwear." },
  { name: "Sleepwear", description: "Clothes for sleeping or lounging." },
  { name: "Accessories", description: "Hats, scarves, gloves, or belts." },
  { name: "Footwear", description: "Shoes, sandals, or boots." },
  { name: "Kidswear", description: "Clothes designed for children." },
];

const mockProducts = [];

const clearDatabase = async () => {
  try {
    await User.deleteMany({});
    await ProductCategory.deleteMany({});
    await Product.deleteMany({});
    console.log("Database cleared!");
  } catch (err) {
    console.error("Error clearing database:", err);
  }
};

const generateUser = async (mockUser) => {
  try {
    const usersWithHashedPasswords = await Promise.all(
      mockUser.map(async (user) => ({
        ...user,
        password: await bcrypt.hash(user.password, 10),
      }))
    );

    await User.insertMany(usersWithHashedPasswords);
    console.log("Users added successfully with hashed passwords!");
  } catch (err) {
    console.error("Error adding users:", err);
  }
};

const generateProductCategories = async (mockProductCategories) => {
  await ProductCategory.insertMany(mockProductCategories);
};

clearDatabase();
generateUser(mockUsers);
generateProductCategories(mockProductCategories);
