name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: Test
      #   run: npm run test

      - name: Save PEM key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > private-key.pem

      - name: Set permissions for PEM key
        run: chmod 600 private-key.pem

      - name: Deliver dist to server
        run: |
          echo "Delivering dist to server"
          scp -i private-key.pem -o StrictHostKeyChecking=no -r dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/dist

      - name: Clean up PEM key
        run: rm private-key.pem

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Save PEM key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > private-key.pem

      - name: Set permissions for PEM key
        run: chmod 600 private-key.pem

      - name: Deploy on server
        run: |
          ssh -i private-key.pem -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ~/dist
            npm install
            node ecosystem.config.js
          EOF

      - name: Clean up PEM key
        run: rm private-key.pem
